// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SCOREgrp05.Data;

#nullable disable

namespace SCOREgrp05.Migrations
{
    [DbContext(typeof(MBContext))]
    [Migration("20231213235637_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("SCOREgrp05.Models.But", b =>
                {
                    b.Property<int>("butId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("joueur")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("matchId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("score")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("temps")
                        .HasColumnType("INTEGER");

                    b.HasKey("butId");

                    b.HasIndex("matchId");

                    b.ToTable("But");
                });

            modelBuilder.Entity("SCOREgrp05.Models.Match", b =>
                {
                    b.Property<int>("matchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("equipe1")
                        .HasColumnType("TEXT");

                    b.Property<string>("equipe2")
                        .HasColumnType("TEXT");

                    b.Property<string>("score")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("temps")
                        .HasColumnType("INTEGER");

                    b.HasKey("matchId");

                    b.ToTable("Match");
                });

            modelBuilder.Entity("SCOREgrp05.Models.But", b =>
                {
                    b.HasOne("SCOREgrp05.Models.Match", "match")
                        .WithMany()
                        .HasForeignKey("matchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("match");
                });
#pragma warning restore 612, 618
        }
    }
}
